export { SigstoreVerifier } from "./sigstore.js";
export type { SigstoreVerifierOptions } from "./sigstore.js";
export type { SigstoreBundle, TLogEntry, VerificationMaterial, MessageSignature, TimestampVerificationData, RFC3161Timestamp } from "./bundle.js";
export type { TrustedRoot, Sigstore, RawTimestampAuthority } from "./interfaces.js";
export {
  VerificationError,
  TimestampError,
  CertificateError,
  TLogError,
  SignatureError,
  PolicyError,
} from "./errors.js";
export { verifyRFC3161Timestamp, verifyBundleTimestamp } from "./timestamp/tsa.js";
export { TrustedRootProvider, type TrustedRootProviderOptions } from "./trust/tuf.js";
export {
  X509Certificate,
  EXTENSION_OID_SCT,
  EXTENSION_OID_FULCIO_ISSUER_V1,
  EXTENSION_OID_GITHUB_WORKFLOW_TRIGGER,
  EXTENSION_OID_GITHUB_WORKFLOW_SHA,
  EXTENSION_OID_GITHUB_WORKFLOW_NAME,
  EXTENSION_OID_GITHUB_WORKFLOW_REPOSITORY,
  EXTENSION_OID_GITHUB_WORKFLOW_REF,
  EXTENSION_OID_OTHERNAME,
  EXTENSION_OID_FULCIO_ISSUER_V2,
  EXTENSION_OID_BUILD_SIGNER_URI,
  EXTENSION_OID_BUILD_SIGNER_DIGEST,
  EXTENSION_OID_RUNNER_ENVIRONMENT,
  EXTENSION_OID_SOURCE_REPOSITORY_URI,
  EXTENSION_OID_SOURCE_REPOSITORY_DIGEST,
  EXTENSION_OID_SOURCE_REPOSITORY_REF,
  EXTENSION_OID_SOURCE_REPOSITORY_IDENTIFIER,
  EXTENSION_OID_SOURCE_REPOSITORY_OWNER_URI,
  EXTENSION_OID_SOURCE_REPOSITORY_OWNER_IDENTIFIER,
  EXTENSION_OID_BUILD_CONFIG_URI,
  EXTENSION_OID_BUILD_CONFIG_DIGEST,
  EXTENSION_OID_BUILD_TRIGGER,
  EXTENSION_OID_RUN_INVOCATION_URI,
  EXTENSION_OID_SOURCE_REPOSITORY_VISIBILITY,
} from "./x509/cert.js";
export {
  X509Extension,
  X509FulcioIssuerV1,
  X509FulcioIssuerV2,
  X509GitHubWorkflowTriggerExtension,
  X509GitHubWorkflowSHAExtension,
  X509GitHubWorkflowNameExtension,
  X509GitHubWorkflowRepositoryExtension,
  X509GitHubWorkflowRefExtension,
  X509BuildSignerURIExtension,
  X509BuildSignerDigestExtension,
  X509RunnerEnvironmentExtension,
  X509SourceRepositoryURIExtension,
  X509SourceRepositoryDigestExtension,
  X509SourceRepositoryRefExtension,
  X509SourceRepositoryIdentifierExtension,
  X509SourceRepositoryOwnerURIExtension,
  X509SourceRepositoryOwnerIdentifierExtension,
  X509BuildConfigURIExtension,
  X509BuildConfigDigestExtension,
  X509BuildTriggerExtension,
  X509RunInvocationURIExtension,
  X509SourceRepositoryVisibilityExtension,
} from "./x509/ext.js";
export { CertificateChainVerifier } from "./x509/chain.js";
export {
  GITHUB_OIDC_ISSUER,
  OIDCIssuer,
  OIDCIssuerV2,
  GitHubWorkflowTrigger,
  GitHubWorkflowSHA,
  GitHubWorkflowName,
  GitHubWorkflowRepository,
  GitHubWorkflowRef,
  OIDCBuildSignerURI,
  OIDCBuildSignerDigest,
  OIDCRunnerEnvironment,
  OIDCSourceRepositoryURI,
  OIDCSourceRepositoryDigest,
  OIDCSourceRepositoryRef,
  OIDCSourceRepositoryIdentifier,
  OIDCSourceRepositoryOwnerURI,
  OIDCSourceRepositoryOwnerIdentifier,
  OIDCBuildConfigURI,
  OIDCBuildConfigDigest,
  OIDCBuildTrigger,
  OIDCRunInvocationURI,
  OIDCSourceRepositoryVisibility,
  AllOf,
  AnyOf,
  Identity,
} from "./policy.js";
export type { VerificationPolicy } from "./policy.js";
